### ISSUE TITLE
unable to install scuttlebot in vagrant

### ISSUE THREAD

**Issue by paidforby** [paidforby/ssb-cljent#1]
vagrant provision fails at following point,
```   
    default: > leveldown@1.7.2 install /usr/lib/node_modules/scuttlebot/node_modules/leveldown
    default: > prebuild-install || node-gyp rebuild
    default: prebuild-install
    default:  
    default: info begin Prebuild-install version 2.4.1
    default: prebuild-install info 
    default: looking for local prebuild @ prebuilds/leveldown-v1.7.2-node-v59-linux-x64.tar.gz
    default: prebuild-install WARN
    default:  install
    default:  EACCES: permission denied, access '/root/.npm'
    default: gyp
    default:  WARN 
    default: EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/9.3.0"
    default: gyp 
    default: WARN
```
and proceeds to blow up terminal with similar errors.
